# Generated by Django 4.0.5 on 2022-06-09 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='a1',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='a10',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='a11',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='a12',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='a13',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='a14',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='a15',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='a16',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='a17',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='a18',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='a2',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='a3',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='a4',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='a5',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='a6',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='a7',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='a8',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='a9',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='b1',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='b10',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='b11',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='b12',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='b13',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='b14',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='b15',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='b16',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='b17',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='b18',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='b2',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='b3',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='b4',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='b5',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='b6',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='b7',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='b8',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='b9',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='c1',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='c10',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='c11',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='c12',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='c13',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='c14',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='c15',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='c16',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='c17',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='c18',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='c2',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='c3',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='c4',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='c5',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='c6',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='c7',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='c8',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='c9',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='d1',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='d10',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='d11',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='d12',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='d13',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='d14',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='d15',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='d16',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='d17',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='d18',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='d2',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='d3',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='d4',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='d5',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='d6',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='d7',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='d8',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='d9',
            field=models.FloatField(default=0, null=True),
        ),
    ]
