# Generated by Django 4.0.4 on 2022-05-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='addr',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='email',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='idid',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='pw',
            field=models.TextField(default='', null=True),
        ),
    ]
