# Generated by Django 4.0.4 on 2022-05-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_remove_post_content_post_addr_post_email_post_idid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='userLevel',
            field=models.FloatField(default=None, null=True),
        ),
    ]
