# Generated by Django 4.0.4 on 2022-05-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_userlevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='musical',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='seat',
            field=models.TextField(default='', null=True),
        ),
    ]
